# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/Administrator/robotics/myrobot

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/Administrator/robotics/myrobot

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Administrator/robotics/myrobot/CMakeFiles /home/Administrator/robotics/myrobot/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Administrator/robotics/myrobot/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kine6_classic

# Build rule for target.
kine6_classic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kine6_classic
.PHONY : kine6_classic

# fast build rule for target.
kine6_classic/fast:
	$(MAKE) -f CMakeFiles/kine6_classic.dir/build.make CMakeFiles/kine6_classic.dir/build
.PHONY : kine6_classic/fast

Classic6dofKine.o: Classic6dofKine.c.o

.PHONY : Classic6dofKine.o

# target to build an object file
Classic6dofKine.c.o:
	$(MAKE) -f CMakeFiles/kine6_classic.dir/build.make CMakeFiles/kine6_classic.dir/Classic6dofKine.c.o
.PHONY : Classic6dofKine.c.o

Classic6dofKine.i: Classic6dofKine.c.i

.PHONY : Classic6dofKine.i

# target to preprocess a source file
Classic6dofKine.c.i:
	$(MAKE) -f CMakeFiles/kine6_classic.dir/build.make CMakeFiles/kine6_classic.dir/Classic6dofKine.c.i
.PHONY : Classic6dofKine.c.i

Classic6dofKine.s: Classic6dofKine.c.s

.PHONY : Classic6dofKine.s

# target to generate assembly for a file
Classic6dofKine.c.s:
	$(MAKE) -f CMakeFiles/kine6_classic.dir/build.make CMakeFiles/kine6_classic.dir/Classic6dofKine.c.s
.PHONY : Classic6dofKine.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/kine6_classic.dir/build.make CMakeFiles/kine6_classic.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/kine6_classic.dir/build.make CMakeFiles/kine6_classic.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/kine6_classic.dir/build.make CMakeFiles/kine6_classic.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... kine6_classic"
	@echo "... rebuild_cache"
	@echo "... Classic6dofKine.o"
	@echo "... Classic6dofKine.i"
	@echo "... Classic6dofKine.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

